/*
Auto-generated by: https://github.com/pmndrs/gltfjsx (customized)
Author: george peaslee (https://sketchfab.com/georgepeaslee)
License: CC-BY-4.0
Source: https://sketchfab.com/3d-models/sand-dune-wanderer-tilt-brush-045dea49a35846d4872ee63fccbbd220
Title: Sand Dune Wanderer - Tilt Brush
*/

import { useGLTF } from "@react-three/drei";
import { JSX, useMemo } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

const MODEL_PATH = "models/sand_dune_wanderer_-_tilt_brush.glb";

type GLTFResult = GLTF & {
  nodes: {
    DoubleTaperedMarker_geo_DoubleTaperedMarker_0: THREE.Mesh;
    DoubleTaperedMarker_geo_DoubleTaperedMarker_0_1: THREE.Mesh;
    Fire_geo_Fire_0: THREE.Mesh;
    Light_geo_Light_0: THREE.Mesh;
    Electricity_geo_Electricity_0: THREE.Mesh;
  };
};

/** Tilt Brush export — vertex colours via MeshBasicMaterial (same fix as Wanderer). */
export function SandDuneWanderer(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(MODEL_PATH) as unknown as GLTFResult;

  const mat = useMemo(
    () =>
      new THREE.MeshBasicMaterial({
        vertexColors: true,
        side: THREE.DoubleSide,
        toneMapped: false,
      }),
    []
  );

  // The figure (explorer) is tiny (~0.64u) and sits at ~[-5.475, 1.142, -0.363]
  // inside an 18u desert. Recenter on the FIGURE so it's at the origin — the
  // desert then extends around it as an immersive backdrop, and the camera can
  // frame the explorer directly instead of the whole dune field.
  return (
    <group {...props} dispose={null}>
      <group position={[5.475, -1.142, 0.363]}>
        <group position={[-5.761, 0, -0.149]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.714}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.DoubleTaperedMarker_geo_DoubleTaperedMarker_0.geometry} material={mat} />
            <mesh geometry={nodes.DoubleTaperedMarker_geo_DoubleTaperedMarker_0_1.geometry} material={mat} />
            <mesh geometry={nodes.Fire_geo_Fire_0.geometry} material={mat} />
            <mesh geometry={nodes.Light_geo_Light_0.geometry} material={mat} />
            <mesh geometry={nodes.Electricity_geo_Electricity_0.geometry} material={mat} />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(MODEL_PATH);
